# Generated by Django 4.2 on 2023-07-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='products')),
                ('offer', models.CharField(max_length=10)),
                ('price_og', models.CharField(max_length=10)),
                ('price', models.IntegerField(max_length=10)),
            ],
        ),
    ]
