# Generated by Django 4.2 on 2023-07-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_a', '0003_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreKing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_k', models.CharField(max_length=200)),
                ('image_k', models.ImageField(upload_to='store')),
                ('offer_k', models.CharField(max_length=10)),
                ('desc_k', models.TextField()),
                ('price_og_k', models.CharField(max_length=10)),
                ('price_k', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StoreQueen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_q', models.CharField(max_length=200)),
                ('image_q', models.ImageField(upload_to='store')),
                ('offer_q', models.CharField(max_length=10)),
                ('desc_q', models.TextField()),
                ('price_og_q', models.CharField(max_length=10)),
                ('price_q', models.IntegerField()),
            ],
        ),
    ]
