# Generated by Django 4.2 on 2023-07-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_a', '0004_storeking_storequeen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_b', models.CharField(max_length=200)),
                ('image_b', models.ImageField(upload_to='banners')),
                ('adv_b', models.TextField()),
            ],
        ),
    ]
